version: "3.8"

# AdGuard uses host networking to access VLAN interfaces directly
# IP addresses (using .2 for consistency across all VLANs) must be configured
# as IP aliases on the host interfaces:
#   - VLAN 5 (Family): 172.16.5.2 (on eth0.5)
#   - VLAN 101 (Guest): 172.16.101.2 (on eth0.101)
#   - VLAN 15 (Management): 172.16.15.2 (on eth0.15)
#
# Note: Docker Swarm doesn't support macvlan networks in service definitions.
# Host networking allows AdGuard to listen on all interfaces, including VLAN interfaces.

services:
  adguard:
    image: adguard/adguardhome:latest
    network_mode: host  # Required to access VLAN interfaces directly
    volumes:
      - /mnt/nas/dockers/adguard/work:/opt/adguardhome/work
      - /mnt/nas/dockers/adguard/conf:/opt/adguardhome/conf
    ports:
      # DNS (UDP/TCP) - required for DNS to work
      - target: 53
        published: 53
        protocol: udp
      - target: 53
        published: 53
        protocol: tcp
      # Web UI - exposed for Traefik routing
      - target: 3000
        published: 3000
        protocol: tcp
      # DNS-over-HTTPS (DoH)
      - target: 443
        published: 8443
        protocol: tcp
      # DNS-over-TLS (DoT)
      - target: 853
        published: 853
        protocol: tcp
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-pi5-01
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      # Note: Traefik service discovery doesn't work with macvlan networks
      # Traefik routes are configured via file provider (see stacks/dynamic/adguard-routes.yml)
      # Web UI is accessible directly at:
      #   - VLAN 5: https://172.16.5.2:3000
      #   - VLAN 101: https://172.16.101.2:3000
      #   - VLAN 15: https://172.16.15.2:3000
      # Or via Traefik proxy: https://adguard-mgmt.specterrealm.com
      labels:
    cap_add:
      - NET_BIND_SERVICE  # Required to bind to port 53
    environment:
      - TZ=${TRAEFIK_TIMEZONE:-UTC}

# Volumes are now using NFS bind mounts instead of local Docker volumes
# This ensures configuration persists across stack redeployments
# volumes:
#   adguard_work:
#     driver: local
#   adguard_conf:
#     driver: local

