version: "3.8"

networks:
  mgmt-network:
    external: true

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    volumes:
      - /mnt/nas/dockers/sonarr/config:/config
      - /mnt/nas/media_streaming:/data/media:ro
      - /mnt/nas/media_streaming/downloads:/data/downloads:rw
      - /mnt/nas/media_streaming/series:/data/tv:rw
      - /mnt/nas/media_streaming/metadata/sonarr:/data/metadata:rw
    networks:
      - mgmt-network
    environment:
      - TZ=${TRAEFIK_TIMEZONE:-UTC}
      - PUID=1000
      - PGID=1000
      - UMASK=002
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=mgmt-network
        - traefik.http.services.sonarr.loadbalancer.server.port=8989
        # HTTPS
        - traefik.http.routers.sonarr.rule=Host(`sonarr.specterrealm.com`)
        - traefik.http.routers.sonarr.entrypoints=websecure
        - traefik.http.routers.sonarr.tls.certresolver=cf
        # HTTP -> HTTPS redirect
        - traefik.http.routers.sonarr-http.rule=Host(`sonarr.specterrealm.com`)
        - traefik.http.routers.sonarr-http.entrypoints=web
        - traefik.http.routers.sonarr-http.service=noop@internal
        - traefik.http.routers.sonarr-http.middlewares=redirect-to-https@file
        - traefik.http.routers.sonarr-http.priority=100

